export interface ICreateSliceProps {}
export interface IAccountingEntriesProps {}
export interface IAdditionalDetailsProps {}
export interface IEmployeeInvolvedProps {}
export interface IFinalEntriesProps {}
export interface IFormalFormProps {}
export interface IPartiesInvolvedProps {}
export interface IRecoveryProps {}
export interface ITransactionEventProps {}
